language: node_js
node_js:
  - "0.10"
  - "0.12"

notifications:
  email:
    - "johnny.estilles@agentia.asia"

addons:
  code_climate:
    repo_token: 60a8e59182c61b0e795d839fb4bffe87ee81bc57abbd322f8222205621827d24

before_script:
  - npm install -g gulp
  - gulp lint

after_script:
  - gulp coverage && codeclimate < ./coverage/lcov.info
